// Wrapper entry: route room WebSocket upgrades straight to the Durable
// Object (Next.js route handlers can't return a 101), and hand everything
// else to the OpenNext-generated Next.js handler.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
// @ts-ignore - generated at build time
import handler from "./.open-next/worker.js";
import type { RoomDO } from "./lib/room-do";

type Env = { ROOM?: DurableObjectNamespace<RoomDO> };

// Room codes are 6 chars from the no-ambiguity alphabet; accept any 6
// alphanumerics here and let idFromName normalise — an unknown code just
// yields an empty DO whose socket never receives anything.
const WS_PATH = /^\/api\/room\/([A-Za-z0-9]{6})\/ws$/;

export default {
  ...handler,
  async fetch(request: Request, env: Env, ctx: unknown): Promise<Response> {
    if (request.headers.get("Upgrade")?.toLowerCase() === "websocket") {
      const m = new URL(request.url).pathname.match(WS_PATH);
      if (m && env.ROOM) {
        const stub = env.ROOM.get(env.ROOM.idFromName(m[1].toUpperCase()));
        return stub.fetch(request);
      }
    }
    return handler.fetch(request, env, ctx);
  },
};
export { RoomDO } from "./lib/room-do";
