// Wrapper entry: re-export the OpenNext-generated Next.js handler as the
// default Worker, plus our Durable Object so wrangler can bind it.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
// @ts-ignore - generated at build time
export { default } from "./.open-next/worker.js";
export { RoomDO } from "./lib/room-do";
